name: Build and Deploy NextJS Frontend

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Sep 1, checkout the respository
      - name: Set Up git
        uses: actions/checkout@v4

      # Step 2, setup BUN
      - name: Set Up BUN
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          cd frontend/
          bun install

      # Step 4: Build
      - name: Build
        run: |
          sudo systemctl stop klowhub-front.service
          # Stop frontend service
          cp ~/proyect/h3-07-klowhub/frontend/.env .
          bun run build

      # # Step 5, save the build folder
      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: next-build
      #     path: ./frontend/.next/ # Save the .next directory as an artifact
      #
      # # Step 6, Download the build folder
      # - name: Download Build Artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: next-build # Download the .next directory

  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Deploy
      - name: Deploy
        run: |
          # Start frontend service
          sudo systemctl start klowhub-front.service
