name: Build and Deploy NextJS Frontend

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Sep 1, checkout the respository
      - name: Set Up git
        uses: actions/checkout@v4

      # Step 2, setup BUN
      - name: Set Up BUN
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          cd frontend/
          bun install

      # Step 4: Stop frontend service
      - name: Build
        run: |
          sudo systemctl stop klowhub-front.service

      # Step 5: Build Frontend
      - name: Build
        run: |
          cd frontend
          cp ~/proyect/h3-07-klowhub/frontend/.env .
          bun run build

      # Step 6: Deploy
      - name: Deploy
        run: |
          # Start frontend service
          sleep 40
          sudo systemctl start klowhub-front.service
